name: Lint Dockerfile

on:
  push:
    paths:
      - 'docker/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Lint
        uses: hadolint/hadolint-action@3.1.0
        with:
          dockerfile: Dockerfile
